version: '3'

services:
  service1:
    image: voyz/ibeam:latest
    environment:
      - ENV_VAR1=value1
      - ENV_VAR2=value2
  service2:
    image: myimage2
    depends_on:
      - service1

      services:
  ibeam:
    container_name: ibeam
    image: voyz/ibeam
    environment:
      - IBEAM_ACCOUNT=aibapi002
      - IBEAM_PASSWORD=layla1966
    ports:
      - "5000:5000"
    network_mode: bridge
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    # expose:
    #   - "5000"
    # networks:
    #   - mynetwork # Required due to clientportal.gw IP restrictions

  # ibkr_service:
  #   container_name: ibkr_service
  #   build: ./
  #   depends_on:
  #     - ibeam
  #   environment:
  #     - IBKR_CASH_ACCOUNT_ID=U2046687
  #     - IBEAM_HOST=https://d2da-142-188-123-105.ngrok.io
  #   ports:
  #     - "80:80"
    # network_mode: "service:ibeam"
    # networks:
    #   - mynetwork # Required due to clientportal.gw IP restrictions

# networks:
#   mynetwork:
#     driver: bridge
