import os

# General Parameters
SLEEP_SECONDS = int(os.getenv("SLEEP_SECONDS"))
RETRY_COUNT = int(os.getenv("RETRY_COUNT"))

# Client Settings
TRADING_CLIENT = os.getenv("TRADING_CLIENT")
MARKET_DATA_CLIENT = os.getenv("MARKET_DATA_CLIENT")
STORAGE_CLIENT = os.getenv("STORAGE_CLIENT")


# IBKR REST Client Settings
IBKR_ACCOUNT_ID = os.getenv("IBKR_ACCOUNT_ID")
IBEAM_HOST = os.getenv("IBEAM_HOST")

# MongoDB Client Settings
MONGO_CONNECTION_STRING = os.getenv("MONGO_CONNECTION_STRING")
MONGO_DATABASE = os.getenv("MONGO_DATABASE")
MONGO_DATABASE_COLLECTION_ORDER_DATA = os.getenv("MONGO_DATABASE_COLLECTION_ORDER_DATA")
MONGO_DATABASE_COLLECTION_STRATEGY_DATA = os.getenv(
    "MONGO_DATABASE_COLLECTION_STRATEGY_DATA"
)

# FMP Client Settings
FMP_API_KEY = os.getenv("FMP_API_KEY")
