import os

# General Parameters
SLEEP_SECONDS = int(os.getenv("SLEEP_SECONDS"))
RETRY_COUNT = int(os.getenv("RETRY_COUNT"))

# Client Settings
TRADING_CLIENT = os.getenv("TRADING_CLIENT")
MARKET_DATA_CLIENT = os.getenv("MARKET_DATA_CLIENT")
STORAGE_CLIENT = os.getenv("STORAGE_CLIENT")


# IBKR REST Client Settings
IBKR_ACCOUNT_ID = os.getenv("IBKR_ACCOUNT_ID")
IBEAM_HOST = os.getenv("IBEAM_HOST")

# MongoDB Client Settings
MONGO_USERNAME = os.getenv("MONGO_USERNAME")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")
MONGO_CLUSTER = os.getenv("MONGO_CLUSTER")
MONGO_DATABASE = os.getenv("MONGO_DATABASE")
MONGO_DATABASE_COLLECTION = os.getenv("MONGO_DATABASE_COLLECTION")
MONGO_DATABASE_COLLECTION_STRATEGY_DATA = os.getenv(
    "MONGO_DATABASE_COLLECTION_STRATEGY_DATA"
)
