import os

SLEEP_SECONDS = 2
RETRY_COUNT = 3

IBKR_CASH_ACCOUNT_ID = os.getenv("IBKR_CASH_ACCOUNT_ID")
IBEAM_HOST = os.getenv("IBEAM_HOST")

MONGO_USERNAME = os.getenv("MONGO_USERNAME")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")
MONGO_CLUSTER = os.getenv("MONGO_CLUSTER")
MONGO_DATABASE = os.getenv("MONGO_DATABASE")
MONGO_DATABASE_COLLECTION = os.getenv("MONGO_DATABASE_COLLECTION")
